# Generated by Django 2.0.7 on 2018-09-22 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edensystem', '0004_auto_20180922_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='sex',
            field=models.CharField(choices=[('男性', 'male'), ('女性', 'female')], default='male', max_length=6, verbose_name='gender'),
        ),
    ]
