# Generated by Django 2.0.7 on 2018-09-22 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edensystem', '0005_auto_20180922_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='sex',
            field=models.CharField(choices=[('male', 'male'), ('female', 'female')], default='male', max_length=6, verbose_name='gender'),
        ),
    ]
