# Generated by Django 2.0.7 on 2018-09-23 04:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import edensystem.models
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('edensystem', '0006_auto_20180922_1215'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=edensystem.models.get_image)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='profile',
            name='thumbnail',
            field=sorl.thumbnail.fields.ImageField(upload_to=edensystem.models.get_thumbnail),
        ),
    ]
