# Generated by Django 2.0.7 on 2018-09-22 13:18

from django.db import migrations
import edensystem.models
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('edensystem', '0006_auto_20180922_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='thumbnail',
            field=sorl.thumbnail.fields.ImageField(upload_to=edensystem.models.get_filename),
        ),
    ]
