# Generated by Django 2.0.7 on 2018-10-03 07:50

from django.db import migrations, models
import edensystem.models


class Migration(migrations.Migration):

    dependencies = [
        ('edensystem', '0007_auto_20180923_1326'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageForDetecting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=edensystem.models.get_image_for_detecting)),
            ],
        ),
    ]
